# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{objectreload-pagination}
  s.version = "0.1.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mateusz Drozdzynski"]
  s.date = %q{2010-07-22}
  s.email = %q{gems@objectreload.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/pagination.rb",
     "lib/pagination/collection.rb",
     "lib/pagination/enumerable.rb",
     "lib/pagination/relation.rb",
     "lib/pagination/version.rb",
     "lib/pagination/view_helpers.rb",
     "objectreload-pagination.gemspec",
     "test/active_record_extentions_test.rb",
     "test/collection_test.rb",
     "test/lib/view_test_process.rb",
     "test/test_helper.rb",
     "test/view_helpers_test.rb"
  ]
  s.homepage = %q{http://github.com/objectreload/pagination}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple pagination - without changes in controllers}
  s.test_files = [
    "test/active_record_extentions_test.rb",
     "test/collection_test.rb",
     "test/lib/view_test_process.rb",
     "test/test_helper.rb",
     "test/view_helpers_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

